### ISSUE TITLE
微信不能网页登陆了

### ISSUE THREAD

**Issue by captainstdin** [lbbniu/WebWechat#10]
<error><ret>1203</ret><message>为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>

**Comment by lbbniu** [comment]
可以参考 https://wechaty.js.org/2021/04/13/wechaty-uos-web/ 进行修改
